### ISSUE TITLE
Crash when decompressing fonts.

### ISSUE THREAD

**Issue by Sidharth-Saha** [BobbyAnguelov/KRG#4]
An assertion is failing when I run the editor.
Output: "KRG Assert fired: 0 (KRG\Code\System\Render\Fonts\FontDecompressor.cpp:119)
KrugerEditor.exe has triggered a breakpoint."

**Comment by BobbyAnguelov** [comment]
I cannot reproduce this, nor has it occurred to anyone else using the code. This is likely something local to your setup.

Please check that the FontData_XXX.cpp files match exactly those in the repository and that there hasn't been any encoding conversion when you pulled them.

**Comment by Sidharth-Saha** [comment]
Git is not showing any difference between my local repository and the origin but looking at the call stack when it crashes I was able to see that it's crashing when decompressing Roboto bold font.

**Comment by BobbyAnguelov** [comment]
Dont know what to tell you, I cant repro and I have multiple people using it.

I dont know git all that well, so maybe there is an encoding change or something in the file and your UI is ignoring it. It's weird that the first font decompresses fine but the second one breaks. 

Also having some information about OS, VS version, etc.. would be useful.

**Comment by Sidharth-Saha** [comment]
Never mind. Updating to the most recent VS2019 fixed the problem.
